version: "3.8"

services:

  # =========================
  # === INTERNAL SERVICES ===
  # =========================

  db:
    image: postgres
    ports:
      - 8999:5432 # Exposed just for debug purposes!
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: unicalendar_db

  notification:
    build:
      context: ./notification
      dockerfile: ./Dockerfile.dev
    volumes:
      - notification_node_modules:/www/node_modules
      - ./notification:/www
      - ./models:/www/src/models

  unitn_gateway:
    build:
      context: ./unitn-gateway
      dockerfile: ./Dockerfile.dev
    volumes:
      - unitn_gateway_node_modules:/www/node_modules
      - ./unitn-gateway:/www
      - ./models:/www/src/models

  unibz_gateway:
    build:
      context: ./unibz-gateway
      dockerfile: ./Dockerfile.dev
    volumes:
      - unibz_gateway_node_modules:/www/node_modules
      - ./unibz-gateway:/www
      - ./models:/www/src/models

  calendar:
    build:
      context: ./calendar
      dockerfile: ./Dockerfile.dev
    volumes:
      - calendar_node_modules:/www/node_modules
      - ./calendar:/www
      - ./models:/www/src/models


  # ========================
  # === PROXIED SERVICES ===
  # ========================

  authentication:
    build:
      context: ./authentication
      dockerfile: ./Dockerfile.dev
    volumes:
      - authentication_node_modules:/www/node_modules
      - ./authentication:/www
      - ./models:/www/src/models

  universities_gateway:
    build:
      context: ./universities-gateway
      dockerfile: ./Dockerfile.dev
    volumes:
      - universities_gateway_node_modules:/www/node_modules
      - ./universities-gateway:/www
      - ./models:/www/src/models

  courses:
    build:
      context: ./courses
      dockerfile: ./Dockerfile.dev
    volumes:
      - courses_node_modules:/www/node_modules
      - ./courses:/www
      - ./models:/www/src/models

  user:
    build:
      context: ./user
      dockerfile: ./Dockerfile.dev
    volumes:
      - user_node_modules:/www/node_modules
      - ./user:/www
      - ./models:/www/src/models


  # ========================
  # === EXPOSED SERVICES ===
  # ========================

  core:
    build:
      context: ./core
      dockerfile: ./Dockerfile.dev
    ports:
      - 8082:80
    volumes:
      - core_node_modules:/www/node_modules
      - ./core:/www
      - ./models:/www/src/models

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    ports:
      - 8081:3000
    volumes:
      - frontend_node_modules:/www/node_modules
      - ./frontend:/www
      - ./models:/www/src/models

volumes:
  notification_node_modules:
  unitn_gateway_node_modules:
  unibz_gateway_node_modules:
  calendar_node_modules:
  authentication_node_modules:
  universities_gateway_node_modules:
  courses_node_modules:
  user_node_modules:
  core_node_modules:
  frontend_node_modules:
