version: "3.8"

services:

  # =========================
  # === INTERNAL SERVICES ===
  # =========================

  db:
    image: postgres
    ports:
      - 8999:5432 # Exposed just for debug purposes!
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: unicalendar_db

  notification:
    build:
      context: ./notification
    volumes:
      - /www/node_modules
      - ./notification:/www
      - ./models:/www/src/models

  unitn_gateway:
    build:
      context: ./unitn-gateway
    volumes:
      - /www/node_modules
      - ./unitn-gateway:/www
      - ./models:/www/src/models

  unibz_gateway:
    build:
      context: ./unibz-gateway
    volumes:
      - /www/node_modules
      - ./unibz-gateway:/www
      - ./models:/www/src/models

  calendar:
    build:
      context: ./calendar
    volumes:
      - /www/node_modules
      - ./calendar:/www
      - ./models:/www/src/models


  # ========================
  # === PROXIED SERVICES ===
  # ========================

  authentication:
    build:
      context: ./authentication
    volumes:
      - /www/node_modules
      - ./authentication:/www
      - ./models:/www/src/models

  universitites_gateway:
    build:
      context: ./universities-gateway
    volumes:
      - /www/node_modules
      - ./universities-gateway:/www
      - ./models:/www/src/models

  courses:
    build:
      context: ./courses
    volumes:
      - /www/node_modules
      - ./courses:/www
      - ./models:/www/src/models

  user:
    build:
      context: ./user
    volumes:
      - /www/node_modules
      - ./user:/www
      - ./models:/www/src/models


  # ========================
  # === EXPOSED SERVICES ===
  # ========================

  core:
    build:
      context: ./core
    ports:
      - 8082:80
    volumes:
      - /www/node_modules
      - ./core:/www
      - ./models:/www/src/models

  frontend:
    build:
      context: ./frontend
    ports:
      - 8081:3000
    volumes:
      - /www/node_modules
      - ./frontend:/www
      - ./models:/www/src/models
