openapi: 3.0.0
info:
  title: AuthenticationService
  version: '1.0'
  description: Service used for user authentication
servers:
  - url: 'http://localhost:8081'
paths:
  /google/oauth:
    post:
      summary: Google OAuth
      operationId: post-google-login
      responses:
        '200':
          description: OK
      description: |-
        Does the redirect to Google Login page

        Used to perform the login of the user via Google OAuth
        @See http://www.passportjs.org/docs/google/
    parameters: []
  /google/callback:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
      operationId: get-google-callback
      description: |-
        Does the redirect to "error page" or "authenticated page" (and saves the google id into the db)

        Request body depends on google oauth results (error or user data)
components:
  schemas:
    User:
      description: All the stored information regarding the user
      type: object
      title: User
      properties:
        id:
          type: number
        username:
          type: string
        email:
          type: string
        password:
          type: string
        googleId:
          type: string
        lastName:
          type: string
        firstName:
          type: string
        university:
          type: string
        confirmed:
          type: boolean
        confirmationToken:
          type: string
      required:
        - username
        - email
        - password
        - googleId
        - lastName
        - firstName
        - university
        - confirmed
        - confirmationToken
  securitySchemes: {}
