openapi: 3.0.0
info:
  title: AuthenticationService
  version: '1.0'
  description: Service used for user authentication (via Google OAuth 2.0). Accessible from the outside.
servers:
  - url: 'http://localhost:8081'
paths:
  /google/oauth:
    post:
      summary: Google OAuth
      operationId: post-google-login
      responses:
        '307':
          description: Temporary Redirect
      description: |-
        Used to perform the login of the user via Google OAuth, it will redirect the user to Google Login page.
        See http://www.passportjs.org/docs/google/#oauth-2-0 (see Oauth 2.0, NOT 1.0)
    parameters: []
  /google/callback:
    get:
      summary: Google OAuth Callback
      tags: []
      responses:
        '307':
          description: Temporary Redirect
      operationId: get-google-callback
      description: |-
        Redirect the user to "error page" or "authenticated page" (and saves the google id into the db).
        Request body depends on Google OAuth Results (error or user data), but they are managed directly by PassportJS.
        See http://www.passportjs.org/docs/google/#oauth-2-0 (see Oauth 2.0, NOT 1.0)
components:
  schemas:
    User:
      description: All the stored information regarding the user
      type: object
      title: User
      properties:
        email:
          type: string
        googleId:
          type: string
        lastName:
          type: string
        firstName:
          type: string
        university:
          $ref: ./UniversitiesGatewayServices.v1.yaml#/components/schemas/University
        id:
          type: number
        picture:
          type: string
        telegramToken:
          type: string
      required:
        - email
        - googleId
        - lastName
        - firstName
        - university
        - id
  securitySchemes: {}
