openapi: 3.0.0
info:
  title: CalendarService
  version: '1.0'
  description: Service used in order to create Google Calendar events inside of the user Calendar. Not exposed outside to the outside.
servers:
  - url: 'http://calendar'
paths:
  '/event/{userId}':
    post:
      summary: Create a new event
      operationId: post-event
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventCreation'
          application/xml:
            schema:
              $ref: '#/components/schemas/EventCreation'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/EventCreation'
      description: Internal route. Create a new event in the Google Calendar.
    parameters:
      - schema:
          type: number
        name: userId
        in: path
        required: true
        description: User ID
  '/clear/{userId}':
    parameters:
      - schema:
          type: number
        name: userId
        in: path
        required: true
        description: User ID
    post:
      summary: Clear events
      operationId: post-clear
      responses:
        '200':
          description: OK
      description: Internal route. Clear all events in the Google Calendar.
components:
  schemas:
    EventCreation:
      description: ''
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        startTime:
          type: number
        endTime:
          type: number
        link:
          type: string
        location:
          type: string
        asynchronous:
          type: boolean
        color:
          type: string
      required:
        - name
        - startTime
        - endTime
  securitySchemes:
    Google OAuth 2.0:
      type: oauth2
      description: ''
security:
  - API Key - 1: []
