openapi: 3.0.0
info:
  title: CoreService.v1
  version: '1.0'
  description: |-
    The process centric service that manage the different tasks of UniCalendar.
    In particular, it will redirect the requests to the other services when needed and execute some scheduled tasks.
servers:
  - url: 'http://localhost:3000'
paths:
  /uni/*:
    get:
      summary: Redirect to UniversitiesGatewayService
      tags: []
      responses: {}
      operationId: get-uni
    post:
      summary: Redirect to UniversitiesGatewayService
      operationId: post-uni
      description: ''
    parameters: []
  /auth/*:
    get:
      summary: Redirect to AuthenticationService
      tags: []
      responses: {}
      operationId: get-auth-*
    post:
      summary: Redirect to AuthenticationService
      operationId: post-auth-*
      description: ''
  /courses/*:
    get:
      summary: Redirect to CoursesService
      tags: []
      responses: {}
      operationId: get-courses-*
    post:
      summary: Redirect to CoursesService
      operationId: post-courses-*
  /user/*:
    get:
      summary: Redirect to UserService
      tags: []
      responses: {}
      operationId: get-user
    parameters: []
    post:
      summary: Redirect to UserService
      operationId: post-user-*
      description: ''
components:
  schemas: {}
  securitySchemes:
    Google OAuth 2.0:
      type: oauth2
