openapi: 3.0.0
info:
  title: CoreService.v1
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /calendar/update:
    get:
      summary: Update user calendar
      tags: []
      responses: {}
      operationId: get-updateCalendar
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
      security:
        - Google Oauth: []
      description: Trigger the update of the user calendar. The user is identified by its Google token in the Authorization header of the request.
    parameters: []
  /calendar/settings:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-user-settings
      security:
        - Google Oauth: []
    parameters: []
    post:
      summary: ''
      operationId: post-calendar-settings
      responses:
        '200':
          description: OK
      security:
        - Google Oauth: []
  /user/settings:
    get:
      summary: Set user settings
      tags: []
      responses: {}
      operationId: get-user-settings
      security:
        - Google Oauth: []
      description: ''
components:
  schemas: {}
  securitySchemes:
    Google Oauth:
      type: oauth2
