openapi: 3.0.0
info:
  title: CoreService.v1
  version: '1.0'
  description: |-
    The process centric service that manage the different tasks of UniCalendar.

    In particular, it will redirect the requests to the other services when needed.
    Some of its endpoints are not exposed but instead they're used internally as scheduled tasks.
servers:
  - url: 'http://localhost:3000'
paths:
  /process/notify:
    get:
      summary: Trigger user notifications
      tags: []
      responses:
        '200':
          description: OK
      operationId: get-user-notify
      description: Trigger the sending of notifications (if needed) of the user events. The user is identified by its Google token in the Authorization header of the request. Also time-scheduled.
      security:
        - Google OAuth 2.0: []
    parameters: []
  /process/update:
    get:
      summary: Trigger update user calendar
      tags: []
      responses:
        '200':
          description: OK
      operationId: get-update-user-calendar
      security:
        - Google OAuth 2.0: []
      description: Trigger the update of the user calendar. The user is identified by its Google token in the Authorization header of the request. Also time-scheduled.
    parameters: []
components:
  schemas: {}
  securitySchemes:
    Google OAuth 2.0:
      type: oauth2
