openapi: 3.0.0
info:
  title: CoursesService
  version: '1.0'
  description: |-
    Manage the calendar of the user, allowing the user to choose which course to follow and the specific configurations for each of them.
    The Google token of the user is given in the Authorization header of the request.
servers:
  - url: 'http://localhost:3000'
paths:
  /courses:
    parameters: []
    get:
      summary: List followed courses
      operationId: get-calendar-courses
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CourseSettings'
      description: Get the list of the followed courses. The Google token of the user is given in the Authorization header of the request.
      security:
        - Google OAuth 2.0: []
    post:
      summary: Add followed course
      operationId: post-calendar-courses
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CourseSettings'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CourseSettingsCreation'
      security:
        - Google OAuth 2.0: []
      description: Add a course to the followed courses list. The Google token of the user is given in the Authorization header of the request.
  '/course/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Get followed course
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CourseSettings'
      operationId: get-calendar-courses-id
      description: Get the details of a followed course. The Google token of the user is given in the Authorization header of the request.
      security:
        - Google OAuth 2.0: []
    delete:
      summary: Delete followed course
      operationId: delete-calendar-course-id
      responses:
        '200':
          description: OK
      description: Delete the course from the followed courses. The Google token of the user is given in the Authorization header of the request.
      security:
        - Google OAuth 2.0: []
    put:
      summary: Update followed course
      operationId: put-calendar-course-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CourseSettings'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CourseSettingsCreation'
      description: Update the followed course settings. The Google token of the user is given in the Authorization header of the request.
      security:
        - Google OAuth 2.0: []
components:
  securitySchemes:
    Google OAuth 2.0:
      type: oauth2
  schemas:
    CourseSettings:
      title: CourseSettings
      type: object
      properties:
        id:
          type: number
        university:
          $ref: ./UniversitiesGatewayServices.v1.yaml#/components/schemas/University
        courseId:
          type: string
        asyncronous:
          type: boolean
        link:
          type: string
        bgColor:
          type: string
        fgColor:
          type: string
        notifyBefore:
          type: number
        notifyTelegram:
          type: boolean
        notifyEmail:
          type: string
      required:
        - id
        - university
        - courseId
    CourseSettingsCreation:
      title: CourseSettingsCreation
      type: object
      properties:
        universitySlug:
          type: string
        courseId:
          type: string
        asyncronous:
          type: boolean
        link:
          type: string
        bgColor:
          type: string
        fgColor:
          type: string
        notifyBefore:
          type: number
        notifyTelegram:
          type: boolean
        notifyEmail:
          type: string
      required:
        - universitySlug
        - courseId
