openapi: 3.0.0
info:
  title: EventsService
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:8082'
paths:
  /event:
    post:
      summary: Create a new event
      operationId: post-event
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
          application/xml:
            schema:
              $ref: '#/components/schemas/EventCreation'
      security:
        - JWT Token: []
      description: Create a new event in the Google Calendar
components:
  schemas:
    EventCreation:
      description: ''
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        startTime:
          type: number
        endTime:
          type: number
        url:
          type: string
        location:
          type: string
        asynchronous:
          type: boolean
        university:
          type: string
        course:
          type: string
        googleToken:
          type: string
      required:
        - name
        - startTime
        - endTime
        - university
        - course
        - googleToken
  securitySchemes:
    JWT Token:
      type: oauth2
      description: ''
security:
  - API Key - 1: []
