openapi: 3.0.0
info:
  title: NotificationService
  version: '1.0'
  description: Service used in order to send notifications to the users. Not exposed outside to the outside.
servers:
  - url: 'http://localhost:8084'
paths:
  /telegram:
    post:
      summary: Send a Telegram notification
      operationId: post-telegram
      description: |-
        Send a Telegram notification to the user.
        The Google token of the user is given in the Authorization header of the request.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TelegramNotification'
        description: ''
      responses:
        '200':
          description: OK
    parameters: []
  /email:
    post:
      summary: Send an email notification
      operationId: post-email
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailNotification'
        description: ''
      description: |-
        Send an email to the user.
        The Google token of the user is given in the Authorization header of the request.
  /telegram/credentials:
    post:
      summary: Get new Telegram credentials
      operationId: post-telegram-credentials
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                  secret:
                    type: string
                  expires:
                    type: string
                  id:
                    type: number
      description: Used for the generation of a 6-digits secret string to be used in the Telegram bot in the /start command (e.g. '/start 130593'). This code is used to bind the user to a specific Telegram chatID. The validity of that token is 2 minutes.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
        description: ''
components:
  schemas:
    TelegramNotification:
      title: TelegramNotification
      type: object
      description: ''
      x-examples: {}
      properties:
        message:
          type: string
        userId:
          type: string
      required:
        - message
        - userId
    EmailNotification:
      title: EmailNotification
      type: object
      properties:
        message:
          type: string
        subject:
          type: string
        recipient:
          type: string
      required:
        - message
        - subject
        - recipient
  securitySchemes:
    Google OAuth 2.0:
      type: oauth2
