openapi: 3.0.0
info:
  title: UniTNGatewayService
  version: '1.0'
  description: Gateway for obtaining courses and schedules of courses of Università degli Studi di Trento. Not exposed outside to the outside.
servers:
  - url: 'http://unitn_gateway'
paths:
  /courses:
    get:
      summary: Get list of courses
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./UniversitiesGatewayService.v1.yaml#/components/schemas/Course
      operationId: get-courses
      description: Internal route. Get the list of courses of UniTN.
  '/course/{id}':
    get:
      summary: Get course events by course ID
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./UniversitiesGatewayService.v1.yaml#/components/schemas/CourseEvent
      operationId: get-course
      description: Internal route. Get the schedule of a course of UniTN.
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Course ID
  /info:
    get:
      summary: Get university's info
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./UniversitiesGatewayService.v1.yaml#/components/schemas/UniversityCreation
      operationId: get-info
      description: Internal route. Get the university's info.
components:
  schemas: {}
