openapi: 3.0.0
info:
  title: UniversitiesGatewayService
  version: '1.0'
  description: Used to obtain a list of the available university gateways and redirect the requests to the correct gateway. Not exposed outside to the outside.
servers:
  - url: 'http://universities_gateway'
paths:
  /universities:
    parameters: []
    get:
      summary: List of universities
      operationId: get-universities
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/University'
      description: Obtain a list of universities available.
  /university:
    post:
      summary: Add a new University
      operationId: post-university
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/University'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UniversityCreation'
      description: Used to register a new university gateway. This endpoint will be automatically called as soon as a gateway start.
  '/university/{universitySlug}/courses':
    get:
      summary: List of courses for a specific university
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'
      operationId: get-courses
      description: Obtain a list of courses of a specific university given by its slug.
    parameters:
      - schema:
          type: string
        name: universitySlug
        in: path
        required: true
  '/university/{universitySlug}/course/{courseId}/events':
    parameters:
      - schema:
          type: string
        name: courseId
        in: path
        required: true
      - schema:
          type: string
        name: universitySlug
        in: path
        required: true
    get:
      summary: Get schedules for a specific course and university
      tags: []
      responses: {}
      operationId: get-university-id-course-id
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CourseEvent'
        description: OK
      description: Get list of events for a specific course and university.
  '/university/{universitySlug}/course/{courseId}':
    parameters:
      - schema:
          type: string
        name: courseId
        in: path
        required: true
      - schema:
          type: string
        name: universitySlug
        in: path
        required: true
    get:
      summary: Get specific course of a specific university
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
      operationId: get-university-slug-course-courseId
      description: Obtain the details of a course of a specific university given by the university slug and the course ID.
components:
  schemas:
    University:
      description: ''
      type: object
      properties:
        slug:
          type: string
        shortName:
          type: string
        fullName:
          type: string
        serverURI:
          type: string
        lastActivity:
          type: string
      required:
        - slug
        - shortName
        - fullName
        - serverURI
        - lastActivity
    UniversityCreation:
      title: UniversityCreation
      type: object
      properties:
        slug:
          type: string
        shortName:
          type: string
        fullName:
          type: string
        serverURI:
          type: string
      required:
        - slug
        - shortName
        - fullName
        - serverURI
    Course:
      description: ''
      type: object
      properties:
        id:
          type: string
          minLength: 1
        name:
          type: string
          minLength: 1
        professor:
          type: string
          minLength: 1
        university:
          $ref: '#/components/schemas/UniversityCreation'
      required:
        - id
        - name
        - professor
        - university
    CourseEvent:
      title: CourseEvent
      type: object
      properties:
        name:
          type: string
        startTime:
          type: number
        endTime:
          type: number
        location:
          type: string
        university:
          $ref: '#/components/schemas/UniversityCreation'
        course:
          type: string
      required:
        - name
        - startTime
        - endTime
        - university
        - course
  securitySchemes: {}
