openapi: 3.0.0
info:
  title: GatewaysServices
  version: '1.0'
servers:
  - url: 'http://localhost:8083'
paths:
  /universities:
    parameters: []
    get:
      summary: Get list of universities
      operationId: get-universities
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/University'
  /university:
    post:
      summary: Add a new University
      operationId: post-university
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/University'
      security:
        - Admin Key: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UniversityCreation'
  'university/{id}/courses':
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'
      operationId: 'get-courses-:id'
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
  '/university/{universityId}/course/{courseId}':
    parameters:
      - schema:
          type: string
        name: universityId
        in: path
        required: true
      - schema:
          type: string
        name: courseId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-university-id-course-id
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CourseEvent'
components:
  schemas:
    University:
      description: ''
      type: object
      properties:
        id:
          type: number
        shortName:
          type: string
        fullName:
          type: string
        serverURI:
          type: string
      required:
        - id
        - shortName
        - fullName
        - serverURI
    UniversityCreation:
      title: UniversityCreation
      type: object
      properties:
        shortName:
          type: string
        fullName:
          type: string
      required:
        - shortName
        - fullName
    Course:
      description: ''
      type: object
      properties:
        id:
          type: string
          minLength: 1
        name:
          type: string
          minLength: 1
        professor:
          type: string
          minLength: 1
        university:
          type: string
          minLength: 1
      required:
        - id
        - name
        - professor
        - university
    CourseEvent:
      title: CourseEvent
      type: object
      properties:
        name:
          type: string
        startTime:
          type: number
        endTime:
          type: number
        location:
          type: string
        university:
          $ref: ./UniversitiesGatewayServices.v1.yaml#/components/schemas/University
        course:
          type: string
      required:
        - name
        - startTime
        - endTime
        - university
        - course
  securitySchemes:
    Admin Key:
      type: http
      scheme: basic
