openapi: 3.0.0
info:
  title: UserService
  version: '1.0'
  description: |-
    Manage the user settings.
    The Google token of the user is given in the Authorization header of the request.
servers:
  - url: 'http://user'
paths:
  /user/settings:
    get:
      summary: Get user settings
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSettingsGet'
      operationId: get-user-settings
      security:
        - Google OAuth 2.0: []
      description: Get the user settings. The Google token of the user is given in the Authorization header of the request.
    post:
      summary: Set user settings
      operationId: post-user-settings
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSettingsGet'
      security:
        - Google OAuth 2.0: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserSettingsSet'
      description: Set the user settings. The Google token of the user is given in the Authorization header of the request.
components:
  securitySchemes:
    Google OAuth 2.0:
      type: oauth2
  schemas:
    UserSettingsGet:
      title: UserSettingsGet
      type: object
      properties:
        university:
          $ref: ./UniversitiesGatewayService.v1.yaml#/components/schemas/University
    UserSettingsSet:
      title: UserSettingsSet
      type: object
      properties:
        universitySlug:
          type: string
